apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-service
  labels:
    app: my-web-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-service
  template:
    metadata:
      labels:
        app: my-web-service
    spec:
      containers:
      - name: my-web-service
        image: acrtito.azurecr.io/tests:#{Build.BuildId}#
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Service
metadata:
  name: my-web-service
  labels:
    app: my-web-service
spec:
  selector:
    app: my-web-service
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer